### ISSUE TITLE
JB-curriculum discussion

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#1]
Which of these lessons is contained by another in this One True Workshop repo? https://ocean-tracking-network.github.io/jb-acoustic-telemetry/index.html

Which are not, but we do not intend to keep anyway?

Which are not, and we'd like to take some functionality and squeeze it into this curriculum? Where?

@SoftwareMonk @jdpye  @jackVanish

**TOPICS**

- [x] -  "intro" - paragraph form introduction to the workshop contents **adding to ep00**
- [x] - "data manipulation basics" - importing datasets & exploring **in intro to R**
- [x] -  "the glatos package" - false det filter, false_detections() **in intro to glatos**
- [x] - "data analysis using glatos" 
*  use detection_events and explore output w tidyverse/lubridate, looking for fish which may occur at the same station. 
* create useful summary tables. 
*  create abacus plot - ggplot and ggplotly.  **in intro to R**
* create plotly map of detections w hovertext about animal residency, det number etc. #6 
*  Replicated using mapbox & using mapview #6 
- [x] - "network analysis" #28 
* use walleye dataset and receivers as vertices. 
* plot w plotly, recreated w mapview too
- [x] - "matching detections to times" - join the matched detections to station names, then filter out based on deploy and recovery date of the receiver and the detection timestamp. helpful to join "station info" like bottom types etc. onto ur dets
- [x] - "summarising and plotting data" 
* great exploratory summaries, by animal , by station. and more. **added to ep06 and 05**
* Plot using GLATOS' abacus plots, and  **in basic viz and plotting**
* ggplot abaus plots.  **in intro to R**
* also: ggmap plots and MovMap plot **in intro to R**
- [x] - "advanced plotting" - add REI to stations and map. gganimate animations #6 #22 
- [x] -  "additional interpolation and plotting w Vtrack" 
* setup data,  **in more features of glatos**
* abacus plot, **in more features of glatos** daily abacus plot, 
* detectionSummary(), #6 
* dispersalSummary(),  **in more features of glatos**
*  COA calc and map,   **in more features of glatos**
* HRSummary(),  #6 
* map of utilization distributions #6 
- [x] - "animating animal movements" - plot data, ggmap and gganimate for indiv animal paths w walleye data #22 
- [x] - "working w spatial data" - intro to CRS and sf #26

**Comment by CaitlinBate** [comment]
most of these have been either ticketed to re-write, added to OTW, or decided to throw out in #6
